// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoSZqhI8t2YGFqmFTIjuLNe_JGKv4hM8o',
    appId: '1:103976883057:web:8fe51d1d0fdf6c67d1dcd0',
    messagingSenderId: '103976883057',
    projectId: 'myproject-d8e18',
    authDomain: 'myproject-d8e18.firebaseapp.com',
    storageBucket: 'myproject-d8e18.firebasestorage.app',
    measurementId: 'G-LK8WCXNJSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSR2X9yuQ2XIfDwGEQNjObdN7SEhcjdx8',
    appId: '1:103976883057:android:e65b96419025b612d1dcd0',
    messagingSenderId: '103976883057',
    projectId: 'myproject-d8e18',
    storageBucket: 'myproject-d8e18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUZpulVKmJKzZ8o7UxUz39XkAt1oJhJE',
    appId: '1:103976883057:ios:780c9034b89a8786d1dcd0',
    messagingSenderId: '103976883057',
    projectId: 'myproject-d8e18',
    storageBucket: 'myproject-d8e18.firebasestorage.app',
    androidClientId: '103976883057-0b62ul5adinj9r396pqkshqmeabaa3pm.apps.googleusercontent.com',
    iosClientId: '103976883057-h146j31gcak9valbrmlflofofkeec3gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickDotTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUZpulVKmJKzZ8o7UxUz39XkAt1oJhJE',
    appId: '1:103976883057:ios:780c9034b89a8786d1dcd0',
    messagingSenderId: '103976883057',
    projectId: 'myproject-d8e18',
    storageBucket: 'myproject-d8e18.firebasestorage.app',
    androidClientId: '103976883057-0b62ul5adinj9r396pqkshqmeabaa3pm.apps.googleusercontent.com',
    iosClientId: '103976883057-h146j31gcak9valbrmlflofofkeec3gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickDotTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoSZqhI8t2YGFqmFTIjuLNe_JGKv4hM8o',
    appId: '1:103976883057:web:0187dc93c37d1c3ed1dcd0',
    messagingSenderId: '103976883057',
    projectId: 'myproject-d8e18',
    authDomain: 'myproject-d8e18.firebaseapp.com',
    storageBucket: 'myproject-d8e18.firebasestorage.app',
    measurementId: 'G-KXYMZHFHLC',
  );

}